excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mikaelmallik.github.io
title: Top BCA Colleges in West Bengal & India
tagline: Courses counseling 
description: My awesome new site
paginate: 5